<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DSLSpecificCoverage" nsURI="https://coverage/DSLSpecificCoverage"
    nsPrefix="DSLSpecificCoverage">
  <eClassifiers xsi:type="ecore:EClass" name="DomainSpecificCoverage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metamodel" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverageMetrics" lowerBound="1"
        upperBound="-1" eType="#//CoverageMetric" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaclass" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//Rule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Condition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InclusionRule" abstract="true" eSuperTypes="#//Rule"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExclusionRule" abstract="true" eSuperTypes="#//Rule"/>
  <eClassifiers xsi:type="ecore:EClass" name="CoverageOfReferenced" eSuperTypes="#//InclusionRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoverageByContent" eSuperTypes="#//InclusionRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containmentReference" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" lowerBound="1"
        eType="#//CoveredContents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ignore" eSuperTypes="#//ExclusionRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignoreSubtypes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LimitedIgnore" eSuperTypes="#//ExclusionRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//LimitationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containerMetaclass" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BranchSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="branches" upperBound="-1"
        eType="#//Branch" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Condition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Branch">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OCLQuery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OCLConstraint" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CoveredContents">
    <eLiterals name="ALL"/>
    <eLiterals name="ONE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LimitationType">
    <eLiterals name="containedBy" literal="ContainedBy"/>
    <eLiterals name="notContainedBy" value="1" literal="NotContainedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoverageMetric" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contexts" upperBound="-1"
        eType="#//Context" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElementCoverage" eSuperTypes="#//CoverageMetric"/>
  <eClassifiers xsi:type="ecore:EClass" name="BranchCoverage" eSuperTypes="#//CoverageMetric">
    <eStructuralFeatures xsi:type="ecore:EReference" name="branchSpecifications" lowerBound="1"
        upperBound="-1" eType="#//BranchSpecification" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
