/*
 * generated by Xtext 2.27.0
 */
package minijava.tcs.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class XMiniJavaAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("minijava/tcs/parser/antlr/internal/InternalXMiniJava.tokens");
	}
}
