/*
 * generated by Xtext 2.28.0
 */
package minitl.tcs.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMinitlScopeProvider extends DelegatingScopeProvider {
}
