/*
 * generated by Xtext 2.28.0
 */
package minitl.tcs.ide

import com.google.inject.Guice
import minitl.tcs.MinitlRuntimeModule
import minitl.tcs.MinitlStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MinitlIdeSetup extends MinitlStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MinitlRuntimeModule, new MinitlIdeModule))
	}
	
}
