/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.example.k3fsm.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class K3FSMIdeModule extends AbstractK3FSMIdeModule {
}
