<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ExecutionTrace" nsURI="www.executiontrace.com" nsPrefix="ExecutionTrace">
  <eClassifiers xsi:type="ecore:EClass" name="Trace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootSteps" lowerBound="1"
        upperBound="-1" eType="#//ExecutionStep" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionStep">
    <eOperations name="getCaller" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eOperations name="getExecutedRule" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1"
        eType="#//ExecutionStep" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
