/**
 * generated by Xtext 2.10.0
 */
package org.imt.xminijava.xtext;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class XMiniJavaStandaloneSetup extends XMiniJavaStandaloneSetupGenerated {
  public static void doSetup() {
    new XMiniJavaStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
