/*
 * generated by Xtext 2.9.1
 */
package minitl.tcs


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MinitlStandaloneSetup extends MinitlStandaloneSetupGenerated {

	def static void doSetup() {
		new MinitlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
