/*
 * generated by Xtext 2.27.0
 */
package minijava.tcs;

import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import minijava.tcs.scoping.XMiniJavaImportedNamespaceAwareLocalScopeProvider;
import minijava.tcs.scoping.XMiniJavaResourceDescriptionsStrategy;

import com.google.inject.Binder;
import com.google.inject.name.Names;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XMiniJavaRuntimeModule extends AbstractXMiniJavaRuntimeModule {
	@Override
	  public void configureIScopeProviderDelegate(final Binder binder) {
	    binder.<IScopeProvider>bind(IScopeProvider.class).annotatedWith(
	      Names.named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE)).to(
	      XMiniJavaImportedNamespaceAwareLocalScopeProvider.class);
	  }

	  public Class<? extends IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
	    return XMiniJavaResourceDescriptionsStrategy.class;
	  }
}
