/*
 * generated by Xtext 2.27.0
 */
package minijava.tcs;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class XMiniJavaStandaloneSetup extends XMiniJavaStandaloneSetupGenerated {

	public static void doSetup() {
		new XMiniJavaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
