/*
 * generated by Xtext 2.27.0
 */
package minijava.tcs.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class XMiniJavaUiModule extends AbstractXMiniJavaUiModule {

	public XMiniJavaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
