/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.example.k3fsm;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class K3FSMStandaloneSetup extends K3FSMStandaloneSetupGenerated {
  public static void doSetup() {
    new K3FSMStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
