/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.example.k3fsm.validation;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class K3FSMValidator extends AbstractK3FSMValidator {
}
