/*
 * generated by Xtext 2.28.0
 */
package minitl.tcs.parser.antlr;

import com.google.inject.Inject;
import minitl.tcs.parser.antlr.internal.InternalMinitlParser;
import minitl.tcs.services.MinitlGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MinitlParser extends AbstractAntlrParser {

	@Inject
	private MinitlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMinitlParser createParser(XtextTokenStream stream) {
		return new InternalMinitlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Transformation";
	}

	public MinitlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MinitlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
