/*
 * generated by Xtext 2.28.0
 */
package minitl.tcs.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MinitlAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("minitl/tcs/parser/antlr/internal/InternalMinitl.tokens");
	}
}
