/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.example.k3fsm.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class K3FSMDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
