/*
 * generated by Xtext 2.25.0
 */
package org.imt.xminijava.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractXMiniJavaScopeProvider extends DelegatingScopeProvider {
}
