/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.example.k3fsm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class K3FSMUiModule extends AbstractK3FSMUiModule {
  public K3FSMUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
