/*
 * generated by Xtext 2.27.0
 */
package minijava.tcs.ui.tests;

import com.google.inject.Injector;
import minijava.tcs.ui.internal.TcsActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class XMiniJavaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TcsActivator.getInstance().getInjector("minijava.tcs.XMiniJava");
	}

}
