/*
 * generated by Xtext 2.25.0
 */
package org.imt.xminijava.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.imt.xminijava.xtext.parser.antlr.internal.InternalXMiniJavaParser;
import org.imt.xminijava.xtext.services.XMiniJavaGrammarAccess;

public class XMiniJavaParser extends AbstractAntlrParser {

	@Inject
	private XMiniJavaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalXMiniJavaParser createParser(XtextTokenStream stream) {
		return new InternalXMiniJavaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public XMiniJavaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XMiniJavaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
