/*
 * generated by Xtext 2.28.0
 */
package minitl.tcs.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MinitlUiModule extends AbstractMinitlUiModule {
}
