/*
 * generated by Xtext 2.25.0
 */
package org.imt.xminijava.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.imt.xminijava.xtext.ui.internal.XtextActivator;

public class XMiniJavaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("org.imt.xminijava.xtext.XMiniJava");
	}

}
