/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.example.k3fsm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.gemoc.example.k3fsm.K3FSMRuntimeModule;
import org.eclipse.gemoc.example.k3fsm.K3FSMStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class K3FSMIdeSetup extends K3FSMStandaloneSetup {
  @Override
  public Injector createInjector() {
    K3FSMRuntimeModule _k3FSMRuntimeModule = new K3FSMRuntimeModule();
    K3FSMIdeModule _k3FSMIdeModule = new K3FSMIdeModule();
    return Guice.createInjector(Modules2.mixin(_k3FSMRuntimeModule, _k3FSMIdeModule));
  }
}
